name: main
on:
  push:
    branches: [ "main" ]

jobs:
  android:
    runs-on: macos-11
    strategy:
      matrix:
        api-level:
          - 34
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13"
          channel: 'stable'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter --no-color test --machine test
